from __future__ import annotations

import shutil
from pathlib import Path
from zoneinfo import ZoneInfo

from .locations import BASE_DIR, ENV_FILE, ROOT_DIR, SECRETS_ENV_FILE
from .parsing import resolve_bin, resolve_path
from .schema import AppSettings
from .secrets import load_required_secrets
from .servers import ServerTarget, build_servers
from .validators import SERVER_KEY_PATTERN

SETTINGS = AppSettings()
SECRETS = load_required_secrets(SECRETS_ENV_FILE, fallback_path=ENV_FILE)

BOT_TOKEN = SECRETS.BOT_TOKEN
ADMIN_PASSWORD = SECRETS.ADMIN_PASSWORD
OWNER_PASSWORD = SECRETS.OWNER_PASSWORD

TZ_NAME = SETTINGS.TZ.strip() or "Europe/Moscow"
TZ = ZoneInfo(TZ_NAME)

DATA_DIR = resolve_path(SETTINGS.DATA_DIR, ROOT_DIR)

MONITOR_CONTAINERS = list(SETTINGS.MONITOR_CONTAINERS)
EXPECTED_A_IP = SETTINGS.EXPECTED_A_IP.strip()
CHECK_A_DOMAINS = list(SETTINGS.CHECK_A_DOMAINS)
DNS_RESOLVERS = list(SETTINGS.DNS_RESOLVERS)

DOCKER_BIN = resolve_bin("/usr/bin/docker", "docker")
UFW_BIN = resolve_bin("/usr/sbin/ufw", "ufw")
SUDO_BIN = shutil.which("sudo") or ""
SSH_BIN = resolve_bin("/usr/bin/ssh", "ssh")

FAIL2BAN_LOG_PATH = SETTINGS.FAIL2BAN_LOG_PATH.strip()
FAIL2BAN_DAILY_AT = SETTINGS.FAIL2BAN_DAILY_AT.strip()
FAIL2BAN_DIGEST_TAIL_LINES = int(SETTINGS.FAIL2BAN_DIGEST_TAIL_LINES)
FAIL2BAN_DIGEST_MAX_BYTES = int(SETTINGS.FAIL2BAN_DIGEST_MAX_BYTES)
DNS_DAILY_REFRESH_AT = SETTINGS.DNS_DAILY_REFRESH_AT.strip()
DNS_STARTUP_REFRESH_DELAY_SEC = SETTINGS.DNS_STARTUP_REFRESH_DELAY_SEC
MAINT_RESTART_NOTIFY_DELAY_SEC = SETTINGS.MAINT_RESTART_NOTIFY_DELAY_SEC
MAINT_RESTART_REMINDER_INTERVAL_SEC = int(SETTINGS.MAINT_RESTART_REMINDER_INTERVAL_SEC)
AUTH_FAIL_WINDOW_SEC = int(SETTINGS.AUTH_FAIL_WINDOW_SEC)
AUTH_MAX_FAILS_IN_WINDOW = int(SETTINGS.AUTH_MAX_FAILS_IN_WINDOW)
AUTH_GLOBAL_MAX_FAILS_IN_WINDOW = int(SETTINGS.AUTH_GLOBAL_MAX_FAILS_IN_WINDOW)
AUTH_LOCKOUT_SEC = int(SETTINGS.AUTH_LOCKOUT_SEC)
AUTH_PRUNE_INTERVAL_SEC = int(SETTINGS.AUTH_PRUNE_INTERVAL_SEC)
ACCESS_REQUEST_COOLDOWN_SEC = int(SETTINGS.ACCESS_REQUEST_COOLDOWN_SEC)
ERROR_NOTIFY_INTERVAL_SEC = int(SETTINGS.ERROR_NOTIFY_INTERVAL_SEC)
OUTBOX_PROCESS_INTERVAL_SEC = int(SETTINGS.OUTBOX_PROCESS_INTERVAL_SEC)
MESSAGE_CLEANUP_ENABLED = bool(SETTINGS.MESSAGE_CLEANUP_ENABLED)
MESSAGE_RETENTION_HOURS = int(SETTINGS.MESSAGE_RETENTION_HOURS)
MESSAGE_CLEANUP_INTERVAL_SEC = int(SETTINGS.MESSAGE_CLEANUP_INTERVAL_SEC)
INSTANCE_LOCK_PATH = resolve_path(
    SETTINGS.INSTANCE_LOCK_PATH or str(Path(DATA_DIR) / "runtime" / "instance.lock"),
    ROOT_DIR,
)
PTB_PERSISTENCE_PATH = resolve_path(
    SETTINGS.PTB_PERSISTENCE_PATH or str(Path(DATA_DIR) / "telegram" / "persistence.pickle"),
    ROOT_DIR,
)
SUBPROC_MAX_OUTPUT_BYTES = int(SETTINGS.SUBPROC_MAX_OUTPUT_BYTES)
STATUS_CACHE_TTL_SEC = int(SETTINGS.STATUS_CACHE_TTL_SEC)
LOG_LEVEL = SETTINGS.LOG_LEVEL
LOG_JSON = bool(SETTINGS.LOG_JSON)
LOCAL_SERVER_CODE = SETTINGS.LOCAL_SERVER_CODE
LOCAL_SERVER_LABEL = SETTINGS.LOCAL_SERVER_LABEL
LOCAL_SERVER_FLAG = SETTINGS.LOCAL_SERVER_FLAG.strip().upper()

REMOTE_SERVER_ENABLED = bool(SETTINGS.REMOTE_SERVER_ENABLED)
REMOTE_SERVER_CODE = SETTINGS.REMOTE_SERVER_CODE
REMOTE_SERVER_LABEL = SETTINGS.REMOTE_SERVER_LABEL
REMOTE_SERVER_FLAG = SETTINGS.REMOTE_SERVER_FLAG.strip().upper()
REMOTE_SERVER_SSH_TARGET = SETTINGS.REMOTE_SERVER_SSH_TARGET.strip()
REMOTE_SERVER_EXPECTED_A_IP = SETTINGS.REMOTE_SERVER_EXPECTED_A_IP.strip()
REMOTE_SERVER_CHECK_A_DOMAINS = list(SETTINGS.REMOTE_SERVER_CHECK_A_DOMAINS)
REMOTE_SERVER_FAIL2BAN_LOG_PATH = SETTINGS.REMOTE_SERVER_FAIL2BAN_LOG_PATH.strip() or "/var/log/fail2ban.log"
REMOTE_SERVER_FAIL2BAN_LOG_PATHS = list(SETTINGS.REMOTE_SERVER_FAIL2BAN_LOG_PATHS)
REMOTE_SERVER_FAIL2BAN_ENABLED = list(SETTINGS.REMOTE_SERVER_FAIL2BAN_ENABLED)
REMOTE_SERVER_FAIL2BAN_TIMEZONES = list(SETTINGS.REMOTE_SERVER_FAIL2BAN_TIMEZONES)
REMOTE_SERVER_MONITOR_CONTAINERS = list(SETTINGS.REMOTE_SERVER_MONITOR_CONTAINERS) or list(MONITOR_CONTAINERS)
REMOTE_SERVER_FLAGS = list(SETTINGS.REMOTE_SERVER_FLAGS)
REMOTE_SERVER_SSH_TARGETS = list(SETTINGS.REMOTE_SERVER_SSH_TARGETS)
REMOTE_SERVER_EXPECTED_A_IPS = list(SETTINGS.REMOTE_SERVER_EXPECTED_A_IPS)
REMOTE_SERVER_DOMAINS = [list(group) for group in SETTINGS.REMOTE_SERVER_DOMAINS]
REMOTE_SERVER_MONITOR_CONTAINERS_BY_SERVER = [
    list(group) for group in SETTINGS.REMOTE_SERVER_MONITOR_CONTAINERS_BY_SERVER
]
REMOTE_SERVER_CODES = list(SETTINGS.REMOTE_SERVER_CODES)
REMOTE_SERVER_LABELS = list(SETTINGS.REMOTE_SERVER_LABELS)

BOT_MODE = SETTINGS.BOT_MODE
REMNAWAVE_METRICS_URL = SETTINGS.REMNAWAVE_METRICS_URL
REMNAWAVE_METRICS_USER = SETTINGS.REMNAWAVE_METRICS_USER
REMNAWAVE_METRICS_PASS = SETTINGS.REMNAWAVE_METRICS_PASS
REMNAWAVE_METRICS_TIMEOUT_SEC = int(SETTINGS.REMNAWAVE_METRICS_TIMEOUT_SEC)
REMNAWAVE_METRICS_CACHE_TTL_SEC = int(SETTINGS.REMNAWAVE_METRICS_CACHE_TTL_SEC)
REMNAWAVE_METRICS_MAX_BYTES = int(SETTINGS.REMNAWAVE_METRICS_MAX_BYTES)
REMNAWAVE_HIDDEN_UUIDS = list(SETTINGS.REMNAWAVE_HIDDEN_UUIDS)
LOCAL_SERVER_REMNAWAVE_UUID = SETTINGS.LOCAL_SERVER_REMNAWAVE_UUID
REMOTE_SERVER_REMNAWAVE_UUIDS = list(SETTINGS.REMOTE_SERVER_REMNAWAVE_UUIDS)
DAILY_NODE_STATUS_REFRESH_AT = SETTINGS.DAILY_NODE_STATUS_REFRESH_AT

SUBPROC_SHORT_TIMEOUT = SETTINGS.SUBPROC_SHORT_TIMEOUT
SUBPROC_MEDIUM_TIMEOUT = SETTINGS.SUBPROC_MEDIUM_TIMEOUT

SSH_STRICT_HOST_KEY_CHECKING = (SETTINGS.SSH_STRICT_HOST_KEY_CHECKING or "").strip() or "yes"
SSH_KNOWN_HOSTS_FILE = (
    resolve_path(SETTINGS.SSH_KNOWN_HOSTS_FILE, ROOT_DIR) if SETTINGS.SSH_KNOWN_HOSTS_FILE.strip() else ""
)
SSH_IDENTITY_FILE = resolve_path(SETTINGS.SSH_IDENTITY_FILE, ROOT_DIR) if SETTINGS.SSH_IDENTITY_FILE.strip() else ""
PRIVILEGED_HELPER_BIN = (SETTINGS.PRIVILEGED_HELPER_BIN or "").strip()

SERVERS: dict[str, ServerTarget] = build_servers(SETTINGS, timezone_name=TZ_NAME)

__all__ = [
    "ACCESS_REQUEST_COOLDOWN_SEC",
    "ADMIN_PASSWORD",
    "AUTH_FAIL_WINDOW_SEC",
    "AUTH_GLOBAL_MAX_FAILS_IN_WINDOW",
    "AUTH_LOCKOUT_SEC",
    "AUTH_MAX_FAILS_IN_WINDOW",
    "AUTH_PRUNE_INTERVAL_SEC",
    "BASE_DIR",
    "BOT_MODE",
    "BOT_TOKEN",
    "CHECK_A_DOMAINS",
    "DAILY_NODE_STATUS_REFRESH_AT",
    "DNS_DAILY_REFRESH_AT",
    "DNS_RESOLVERS",
    "DNS_STARTUP_REFRESH_DELAY_SEC",
    "DOCKER_BIN",
    "ENV_FILE",
    "ERROR_NOTIFY_INTERVAL_SEC",
    "EXPECTED_A_IP",
    "FAIL2BAN_DAILY_AT",
    "FAIL2BAN_DIGEST_MAX_BYTES",
    "FAIL2BAN_DIGEST_TAIL_LINES",
    "FAIL2BAN_LOG_PATH",
    "DATA_DIR",
    "INSTANCE_LOCK_PATH",
    "LOCAL_SERVER_CODE",
    "LOCAL_SERVER_FLAG",
    "LOCAL_SERVER_LABEL",
    "LOCAL_SERVER_REMNAWAVE_UUID",
    "LOG_JSON",
    "LOG_LEVEL",
    "MAINT_RESTART_NOTIFY_DELAY_SEC",
    "MAINT_RESTART_REMINDER_INTERVAL_SEC",
    "MESSAGE_CLEANUP_ENABLED",
    "MESSAGE_CLEANUP_INTERVAL_SEC",
    "MESSAGE_RETENTION_HOURS",
    "MONITOR_CONTAINERS",
    "OUTBOX_PROCESS_INTERVAL_SEC",
    "OWNER_PASSWORD",
    "PRIVILEGED_HELPER_BIN",
    "PTB_PERSISTENCE_PATH",
    "REMNAWAVE_HIDDEN_UUIDS",
    "REMNAWAVE_METRICS_CACHE_TTL_SEC",
    "REMNAWAVE_METRICS_MAX_BYTES",
    "REMNAWAVE_METRICS_PASS",
    "REMNAWAVE_METRICS_TIMEOUT_SEC",
    "REMNAWAVE_METRICS_URL",
    "REMNAWAVE_METRICS_USER",
    "REMOTE_SERVER_CHECK_A_DOMAINS",
    "REMOTE_SERVER_CODE",
    "REMOTE_SERVER_CODES",
    "REMOTE_SERVER_DOMAINS",
    "REMOTE_SERVER_ENABLED",
    "REMOTE_SERVER_EXPECTED_A_IP",
    "REMOTE_SERVER_EXPECTED_A_IPS",
    "REMOTE_SERVER_FAIL2BAN_ENABLED",
    "REMOTE_SERVER_FAIL2BAN_LOG_PATH",
    "REMOTE_SERVER_FAIL2BAN_LOG_PATHS",
    "REMOTE_SERVER_FAIL2BAN_TIMEZONES",
    "REMOTE_SERVER_FLAG",
    "REMOTE_SERVER_FLAGS",
    "REMOTE_SERVER_LABEL",
    "REMOTE_SERVER_LABELS",
    "REMOTE_SERVER_MONITOR_CONTAINERS",
    "REMOTE_SERVER_MONITOR_CONTAINERS_BY_SERVER",
    "REMOTE_SERVER_REMNAWAVE_UUIDS",
    "REMOTE_SERVER_SSH_TARGET",
    "REMOTE_SERVER_SSH_TARGETS",
    "ROOT_DIR",
    "SECRETS",
    "SECRETS_ENV_FILE",
    "SERVER_KEY_PATTERN",
    "SERVERS",
    "SETTINGS",
    "ServerTarget",
    "SSH_BIN",
    "SSH_IDENTITY_FILE",
    "SSH_KNOWN_HOSTS_FILE",
    "SSH_STRICT_HOST_KEY_CHECKING",
    "STATUS_CACHE_TTL_SEC",
    "SUBPROC_MAX_OUTPUT_BYTES",
    "SUBPROC_MEDIUM_TIMEOUT",
    "SUBPROC_SHORT_TIMEOUT",
    "SUDO_BIN",
    "TZ",
    "TZ_NAME",
    "UFW_BIN",
]
