from __future__ import annotations

# Imports such as BASE_DIR and TLSEndpoint are intentionally re-exported.
# ruff: noqa: F401
import shutil
from pathlib import Path
from zoneinfo import ZoneInfo

from .locations import BASE_DIR, BOT_CONFIG_FILE, CONFIG_DIR, ROOT_DIR, SECRETS_ENV_FILE, SERVER_CONFIG_DIR
from .parsing import resolve_bin, resolve_path
from .schema import AppSettings, load_app_settings
from .secrets import load_required_secrets
from .servers import ServerTarget, TLSEndpoint, load_servers, server_monitoring_fingerprint
from .validators import SERVER_KEY_PATTERN

SETTINGS: AppSettings = load_app_settings(BOT_CONFIG_FILE)
SECRETS = load_required_secrets(SECRETS_ENV_FILE)

BOT_TOKEN = SECRETS.BOT_TOKEN
ADMIN_PASSWORD = SECRETS.ADMIN_PASSWORD
OWNER_PASSWORD = SECRETS.OWNER_PASSWORD

TZ_NAME = SETTINGS.TZ.strip() or "Europe/Moscow"
TZ = ZoneInfo(TZ_NAME)

DATA_DIR = resolve_path(SETTINGS.DATA_DIR, ROOT_DIR)
SERVERS: dict[str, ServerTarget] = load_servers(SERVER_CONFIG_DIR, timezone_name=TZ_NAME)
BOT_MODE = "mixed" if any(server.monitoring_source == "remnawave" for server in SERVERS.values()) else "ssh"

DNS_RESOLVERS = list(SETTINGS.DNS_RESOLVERS)
DNS_DAILY_REFRESH_AT = SETTINGS.DNS_DAILY_REFRESH_AT.strip()
DNS_STARTUP_REFRESH_DELAY_SEC = SETTINGS.DNS_STARTUP_REFRESH_DELAY_SEC

DOCKER_BIN = resolve_bin("/usr/bin/docker", "docker")
UFW_BIN = resolve_bin("/usr/sbin/ufw", "ufw")
SUDO_BIN = shutil.which("sudo") or ""
SSH_BIN = resolve_bin("/usr/bin/ssh", "ssh")

FAIL2BAN_DAILY_AT = SETTINGS.FAIL2BAN_DAILY_AT.strip()
FAIL2BAN_DIGEST_TAIL_LINES = int(SETTINGS.FAIL2BAN_DIGEST_TAIL_LINES)
FAIL2BAN_DIGEST_MAX_BYTES = int(SETTINGS.FAIL2BAN_DIGEST_MAX_BYTES)
MAINT_RESTART_NOTIFY_DELAY_SEC = SETTINGS.MAINT_RESTART_NOTIFY_DELAY_SEC
MAINT_RESTART_REMINDER_INTERVAL_SEC = int(SETTINGS.MAINT_RESTART_REMINDER_INTERVAL_SEC)

AUTH_FAIL_WINDOW_SEC = int(SETTINGS.AUTH_FAIL_WINDOW_SEC)
AUTH_MAX_FAILS_IN_WINDOW = int(SETTINGS.AUTH_MAX_FAILS_IN_WINDOW)
AUTH_GLOBAL_MAX_FAILS_IN_WINDOW = int(SETTINGS.AUTH_GLOBAL_MAX_FAILS_IN_WINDOW)
AUTH_LOCKOUT_SEC = int(SETTINGS.AUTH_LOCKOUT_SEC)
AUTH_PRUNE_INTERVAL_SEC = int(SETTINGS.AUTH_PRUNE_INTERVAL_SEC)
ACCESS_REQUEST_COOLDOWN_SEC = int(SETTINGS.ACCESS_REQUEST_COOLDOWN_SEC)
ERROR_NOTIFY_INTERVAL_SEC = int(SETTINGS.ERROR_NOTIFY_INTERVAL_SEC)
OUTBOX_PROCESS_INTERVAL_SEC = int(SETTINGS.OUTBOX_PROCESS_INTERVAL_SEC)

NAVIGATION_CLEANUP_ENABLED = bool(SETTINGS.NAVIGATION_CLEANUP_ENABLED)
NAVIGATION_RETENTION_HOURS = int(SETTINGS.NAVIGATION_RETENTION_HOURS)
NAVIGATION_CLEANUP_INTERVAL_SEC = int(SETTINGS.NAVIGATION_CLEANUP_INTERVAL_SEC)

INSTANCE_LOCK_PATH = resolve_path(
    SETTINGS.INSTANCE_LOCK_PATH or str(Path(DATA_DIR) / "runtime" / "instance.lock"),
    ROOT_DIR,
)
PTB_PERSISTENCE_PATH = resolve_path(
    SETTINGS.PTB_PERSISTENCE_PATH or str(Path(DATA_DIR) / "telegram" / "persistence.pickle"),
    ROOT_DIR,
)
SUBPROC_MAX_OUTPUT_BYTES = int(SETTINGS.SUBPROC_MAX_OUTPUT_BYTES)
SUBPROC_SHORT_TIMEOUT = SETTINGS.SUBPROC_SHORT_TIMEOUT
SUBPROC_MEDIUM_TIMEOUT = SETTINGS.SUBPROC_MEDIUM_TIMEOUT
STATUS_CACHE_TTL_SEC = int(SETTINGS.STATUS_CACHE_TTL_SEC)

LOG_LEVEL = SETTINGS.LOG_LEVEL
LOG_JSON = bool(SETTINGS.LOG_JSON)

REMNAWAVE_METRICS_URL = SETTINGS.REMNAWAVE_METRICS_URL
REMNAWAVE_METRICS_USER = SECRETS.REMNAWAVE_METRICS_USER
REMNAWAVE_METRICS_PASS = SECRETS.REMNAWAVE_METRICS_PASS
REMNAWAVE_METRICS_TIMEOUT_SEC = int(SETTINGS.REMNAWAVE_METRICS_TIMEOUT_SEC)
REMNAWAVE_METRICS_CACHE_TTL_SEC = int(SETTINGS.REMNAWAVE_METRICS_CACHE_TTL_SEC)
REMNAWAVE_METRICS_MAX_BYTES = int(SETTINGS.REMNAWAVE_METRICS_MAX_BYTES)
REMNAWAVE_HIDDEN_UUIDS = list(SETTINGS.REMNAWAVE_HIDDEN_UUIDS)
DAILY_NODE_STATUS_REFRESH_AT = SETTINGS.DAILY_NODE_STATUS_REFRESH_AT
if BOT_MODE == "mixed" and not REMNAWAVE_METRICS_URL:
    raise RuntimeError("a server JSON uses monitoring.source='remnawave', but REMNAWAVE_METRICS_URL is empty")

SSH_STRICT_HOST_KEY_CHECKING = (SETTINGS.SSH_STRICT_HOST_KEY_CHECKING or "").strip() or "yes"
SSH_KNOWN_HOSTS_FILE = (
    resolve_path(SETTINGS.SSH_KNOWN_HOSTS_FILE, ROOT_DIR) if SETTINGS.SSH_KNOWN_HOSTS_FILE.strip() else ""
)
SSH_IDENTITY_FILE = resolve_path(SETTINGS.SSH_IDENTITY_FILE, ROOT_DIR) if SETTINGS.SSH_IDENTITY_FILE.strip() else ""
PRIVILEGED_HELPER_BIN = (SETTINGS.PRIVILEGED_HELPER_BIN or "").strip()

__all__ = [
    "ACCESS_REQUEST_COOLDOWN_SEC",
    "ADMIN_PASSWORD",
    "AUTH_FAIL_WINDOW_SEC",
    "AUTH_GLOBAL_MAX_FAILS_IN_WINDOW",
    "AUTH_LOCKOUT_SEC",
    "AUTH_MAX_FAILS_IN_WINDOW",
    "AUTH_PRUNE_INTERVAL_SEC",
    "BASE_DIR",
    "BOT_CONFIG_FILE",
    "BOT_MODE",
    "BOT_TOKEN",
    "CONFIG_DIR",
    "DAILY_NODE_STATUS_REFRESH_AT",
    "DATA_DIR",
    "DNS_DAILY_REFRESH_AT",
    "DNS_RESOLVERS",
    "DNS_STARTUP_REFRESH_DELAY_SEC",
    "DOCKER_BIN",
    "ERROR_NOTIFY_INTERVAL_SEC",
    "FAIL2BAN_DAILY_AT",
    "FAIL2BAN_DIGEST_MAX_BYTES",
    "FAIL2BAN_DIGEST_TAIL_LINES",
    "INSTANCE_LOCK_PATH",
    "LOG_JSON",
    "LOG_LEVEL",
    "MAINT_RESTART_NOTIFY_DELAY_SEC",
    "MAINT_RESTART_REMINDER_INTERVAL_SEC",
    "NAVIGATION_CLEANUP_ENABLED",
    "NAVIGATION_CLEANUP_INTERVAL_SEC",
    "NAVIGATION_RETENTION_HOURS",
    "OUTBOX_PROCESS_INTERVAL_SEC",
    "OWNER_PASSWORD",
    "PRIVILEGED_HELPER_BIN",
    "PTB_PERSISTENCE_PATH",
    "REMNAWAVE_HIDDEN_UUIDS",
    "REMNAWAVE_METRICS_CACHE_TTL_SEC",
    "REMNAWAVE_METRICS_MAX_BYTES",
    "REMNAWAVE_METRICS_PASS",
    "REMNAWAVE_METRICS_TIMEOUT_SEC",
    "REMNAWAVE_METRICS_URL",
    "REMNAWAVE_METRICS_USER",
    "ROOT_DIR",
    "SECRETS",
    "SECRETS_ENV_FILE",
    "SERVER_CONFIG_DIR",
    "SERVER_KEY_PATTERN",
    "SERVERS",
    "SETTINGS",
    "SSH_BIN",
    "SSH_IDENTITY_FILE",
    "SSH_KNOWN_HOSTS_FILE",
    "SSH_STRICT_HOST_KEY_CHECKING",
    "STATUS_CACHE_TTL_SEC",
    "SUBPROC_MAX_OUTPUT_BYTES",
    "SUBPROC_MEDIUM_TIMEOUT",
    "SUBPROC_SHORT_TIMEOUT",
    "SUDO_BIN",
    "ServerTarget",
    "TLSEndpoint",
    "TZ",
    "TZ_NAME",
    "UFW_BIN",
    "server_monitoring_fingerprint",
]
