"""Subscription plan constants and policy helpers."""

PLAN_MONTHS = 3
PLAN_MONTHLY_RUB = 100
PLAN_TOTAL_RUB = PLAN_MONTHS * PLAN_MONTHLY_RUB
DEFAULT_TRIAL_DURATION_HOURS = 24
MAX_CUSTOM_TRIAL_DURATION_HOURS = 24 * 365
MIN_CUSTOM_TRIAL_DURATION_HOURS = 1

__all__ = [
    "DEFAULT_TRIAL_DURATION_HOURS",
    "MAX_CUSTOM_TRIAL_DURATION_HOURS",
    "MIN_CUSTOM_TRIAL_DURATION_HOURS",
    "PLAN_MONTHLY_RUB",
    "PLAN_MONTHS",
    "PLAN_TOTAL_RUB",
]
